language: java

jdk:
  - openjdk8

before_install:
  - sudo apt-get install jq
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar

script:
  mvn clean verify

cache:
  directories:
    - $HOME/.m2

after_success:
  - java -jar codacy-coverage-reporter-6.0.0-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml

notifications:
  slack:
    rooms:
      - secure: fCkIShAEWKOglVUIuhVlRbwmE86Wu20LF+JwDn1IUzXZrSM9Mt842j0MGm4B0fvVP4UGCMrl4QI6WZQKBcDl2IaQRh6Q+bK7x5qSOBLJdw61oDu//ZWRhFv8S4Uyjm76So3YbWIkQ0RNUIcbmLxVTHVy60Ya2+RU+cWMbireppUGtkNS1Ra26yYGnxd5C+qV/QgGhxz14GBTRR2XQ8+oyn2tUC5NFOZ1NqIAQRAuTeVjAMsI27vaNa5Qjhw0o6JFsZhJyaozpYFhSqPDw0xRTHr52fFXTMFDRiJrXAC1t7UadRqb/joblgBuE2aN7W3OfbuZpRAtzSrCyOdn150Wly2djhPlcT9tMh8ReVf5ijCMIsyxfYhR+RyBXk/jU4SfeWRCRGms3wr8S7c0iqhpNEOMEHWmW3juiF9JFm2RUzxjNNoTf99sVeDZPobQu7MsQ+SDdI9Qm1vZOir0jKL7QkMTUHrrON7nYVGK6nHQvnMKXRzxh/q17I1EZSTH6QGWamphrwJDuMNQGivxpE/EdhgqtvL7RD8/HDCMSH8EhUj7XZibOjOU4CLKCeXZNpSazT6ah21qYgPfLNaePxKiUVHTcLx0h2DVywR6qjDXTx0P7RKdNXGt5XG+YxNTc8c/DXNxAf85zC4eSUIsVByJb66ur5KxTeQlWBnf4lKQ32E=
    on_success: change
    on_failure: always
